name: CI

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  golangci:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run unit tests
        run: |
          go test -v -race -coverprofile=coverage-unit.out -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage-unit.out
          flags: unittests

  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install Atlas CLI
        run: curl -sSf https://atlasgo.sh | sh

      - name: Run integration tests
        run: |
          go test -v -p 1 -tags=integration -coverprofile=coverage-integration.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage-integration.out
          flags: integration

